language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - CI=false npm run build
deploy:
  #master -> release branch deployment
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    repo: dev-launchers/$REPO_NAME
    target_branch: master
    on:
      branch: release
  #masster branch parcel deployment
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    repo: dev-launchers-sandbox/$REPO_NAME
    target_branch: gh-pages
    on:
      branch: master

